name: thesis-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - pyyaml
  - scikit-learn
  - matplotlib
  - torch>=1.8
  - transformers>=4.0
  - norse
  - tensorboard
  - jupyterlab
  - pip:
      - sacred
      - torchmetrics
      - datasets
